### ISSUE TITLE
SEVERE: Container startup failed

### ISSUE THREAD

**Issue by olulofe** [naxhh/jenkins-php-docker#1]
Hello, when i run command ```docker run --name=jenkins-php  -P -p 8081:80 --expose=22 --expose=80 --expose=443 -v /docker/jenkins-php-docker:/var/jenkins_home:rw naxhh/jenkins-php-docker```

I get below error:

```
SEVERE: Container startup failed
java.io.FileNotFoundException: /var/jenkins_home/war/META-INF/MANIFEST.MF (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:277)
	at winstone.HostConfiguration.<init>(HostConfiguration.java:81)
	at winstone.HostGroup.initHost(HostGroup.java:66)
	at winstone.HostGroup.<init>(HostGroup.java:45)
	at winstone.Launcher.<init>(Launcher.java:143)
	at winstone.Launcher.main(Launcher.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at Main._main(Main.java:293)
	at Main.main(Main.java:98)
```

**Comment by naxhh** [comment]
There's been a long long time since I made this. And my docker knowledge by the time was very basic.

So I'm pretty sure you can find a better implementations of this one.

Check the forks o the docker hub.

Regarding your error it seems you are missing something about java
